name: Build and Release macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build macOS app
      run: flutter build macos --release
    
    - name: Create DMG
      run: |
        # Create a DMG for distribution
        hdiutil create -volname "Photo Watermark" -srcfolder build/macos/Build/Products/Release/photo_watermark.app -ov -format UDZO photo_watermark.dmg
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./photo_watermark.dmg
        asset_name: photo_watermark.dmg
        asset_content_type: application/x-apple-diskimage
    
    - name: Upload App Bundle
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/macos/Build/Products/Release/photo_watermark.app
        asset_name: photo_watermark.app.zip
        asset_content_type: application/zip